version: "3.9"
services:
  # MongoDB
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

  mongo-admin:
    image: mongo-express:latest
    ports:
      - 8081:8081
    depends_on:
      - mongo
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      ME_CONFIG_MONGODB_AUTH_PASSWORD: admin

volumes:
  mongo:
